### ISSUE TITLE
I cannot make the input aware of the keyboard opening and asjust the view.

### ISSUE THREAD

**Issue by itokallad** [ammarahm-ed/react-native-actions-sheet#35]
![actionsheet gif](https://user-images.githubusercontent.com/5172175/87515145-bcb0a300-c6be-11ea-9693-22a4e1d65f18.gif)

I am using a mapview with the markers of the restaurants. When clicked on the restaurant marker in the map , i display the actionsheet with input to write some notes. However the keyboard blocks the actionsheet completely. I cannot figure out how to solve the problem.

My Code snippet is as following 

```
const styles = StyleSheet.create({
        container: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            justifyContent: 'flex-end',
            alignItems: 'center',
            flex: 1,
        },
        map: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            flex: 1
        },

    });


    return (
        <View style={styles.container}>
            {
                showCamera &&
                <React.Fragment>
                    <RNCamera
                        captureAudio={false}
                        ref={ref => {
                            this.camera = ref
                        }}
                    />
                    <View style={{ flex: 0, flexDirection: 'row', justifyContent: 'center' }}>
                        <TouchableOpacity onPress={()=>takePicture()}>
                            <Icon name="record-vinyl" size={25}/>
                        </TouchableOpacity>
                    </View>
                </React.Fragment>

            }
            {
                latitude && longitude &&
                <MapView
                    provider={PROVIDER_GOOGLE}
                    initialRegion={{latitude:latitude,longitude:longitude, latitudeDelta: 0.5,longitudeDelta: 0.5}}
                    style={styles.map}
                    showsUserLocation={true}
                >

                    {
                        deliveryAddresses.map((address,locationKey)=>{
                            return (
                                <MapView.Marker
                                    coordinate={{latitude: address.location.lat,longitude: address.location.lng}}
                                    title={address.customer}
                                    description={address.delivery_address}
                                    onPress={()=>onAddressPress(address)}
                                >
                                </MapView.Marker>
                            )
                        })
                    }
                    {
                        polyLines.map((points)=>{
                            const decodedPoints = Polyline.decode(points);
                            const coords = decodedPoints.map((point, index) => {
                                return  {
                                    latitude : point[0],
                                    longitude : point[1]
                                }
                            });
                            return (
                                <MapView.Polyline
                                    coordinates={coords}
                                    strokeColor={'black'}
                                    strokeWidth={4}
                                >

                                </MapView.Polyline>
                            )
                        })
                    }
                </MapView>
            }

            <ActionSheet
                ref={actionSheetRef}

            >
                <ScrollView>
                    {
                        selectedOrder &&
                        <Card>
                            <Content>
                                <CardItem header>
                                    <Text>{'#SO-'+selectedOrder.sales_order_id}</Text>
                                </CardItem>
                                <CardItem>
                                    <Body>
                                    <Text>{selectedOrder.customer}</Text>
                                    <Divider/>
                                    <Text>{selectedOrder.delivery_address}</Text>
                                    </Body>
                                </CardItem>
                                <CardItem>
                                    <Input placeholder="Notes on delivery"/>
                                </CardItem>
                                <CardItem>
                                    <Button iconLeft light onPress={()=>openCamera()}>
                                        <Icon name='camera' size={20} style={{padding:5}}/>
                                        <Text>Take Photo</Text>
                                    </Button>
                                </CardItem>

                                <CardItem>
                                    <Button iconLeft onPress={()=>markOrderAsDelivered(selectedOrder.sales_order_id)}
                                            style={{backgroundColor:'#1AB394'}}
                                    >
                                        <Icon name="check" size={20} color={'#ffff'} style={{padding:5}}/>
                                        <Text>Mark as Delivered</Text>
                                    </Button>
                                </CardItem>
                            </Content>
                        </Card>

                    }
                </ScrollView>

            </ActionSheet>
        </View>

```

**Comment by ammarahm-ed** [comment]
Send a gif/video to demonstrate the issue you are facing.

**Comment by Cookizza** [comment]
Any update on this? Currently it's not possible to take input on the action sheet on android, as the keyboard covers the action sheet.

**Comment by ammarahm-ed** [comment]
i will fix this, its caused by the `KeyboardAvoidingView` being disabled.

**Comment by ammarahm-ed** [comment]
Fixed

**Comment by itokallad** [comment]
Still The keyboard covers the action sheet. 
Could you actually show me that it is fixed ? 
Probably some demo 
Thanks

**Comment by simuxs** [comment]
I have the same issue.

**Comment by ammarahm-ed** [comment]
@itokallad Have you tried the example app?

**Comment by johhansantana** [comment]
Is anyone having this issue still? I am in 0.8.29 and the keyboard goes on top of the drawer in Android.

Mind you I have removed every SafeAreaView and KeyboardAvoidingView I could find and still the same result.


https://github.com/ammarahm-ed/react-native-actions-sheet/assets/9933887/80a49a86-84c3-44b2-a48a-69e51a41ca29

**Comment by NoatToan** [comment]
> Is anyone having this issue still? I am in 0.8.29 and the keyboard goes on top of the drawer in Android.
> 
> Mind you I have removed every SafeAreaView and KeyboardAvoidingView I could find and still the same result.
> 
>  CleanShot.2023-09-25.at.16.24.51.mp4

Same issue with you :(
