### ISSUE TITLE
Indicator position

### ISSUE THREAD

**Issue by mateattilabarna** [ammarahm-ed/react-native-actions-sheet#88]
Hi @ammarahm-ed !

I'm trying to create an action sheet with your package. When i set the height to a higher value, the indicator renders 'x' pixels lower (I think because of the **indicatorTranslateY**):

indicator at the top:
![iphone11_2](https://user-images.githubusercontent.com/19281761/121661227-4837dd00-caa4-11eb-8e33-b49fed8115eb.png)

indicator renders lower:

![iphone11_1](https://user-images.githubusercontent.com/19281761/121661166-37876700-caa4-11eb-9cf9-05680f4668ac.png)

Is this intentionally? I think you check the distance between the action sheet and the top of the screen and based on that the indicator renders couple of pixels lower. We would like to have the indicator always at the top of the action sheet. Is there any chance, to have for example an 'indicatorPositionAlwaysTop'(boolean) attribute which we can set from outside? I'm also open to contribute to this library, so i can make a PR for this solution. What's your opinion?

**Comment by ammarahm-ed** [comment]
I will look into this. There is probably some miscalculation here causing the indicator to come down sooner than it should.

**Comment by mateattilabarna** [comment]
@ammarahm-ed  thank you! just ping me here if i can help or i should do this change!

**Comment by mateattilabarna** [comment]
@ammarahm-ed Sorry for bothering you, maybe can you give an approximate date, when this will be fixed?

**Comment by ammarahm-ed** [comment]
Hey @mateattilabarna I have fixed it on master. Can you test it, it is working fine for me.

**Comment by mateattilabarna** [comment]
Hi @ammarahm-ed ,

Thanks! Unfortunately I see the same error with the latest master branch:

![Screenshot 2021-06-22 at 15 56 38](https://user-images.githubusercontent.com/19281761/122938145-d0ef2c80-d372-11eb-987c-c9dce39014a9.png)

I checked the node modules folder, I can see the modifications what you have made, e.g.:

![Screenshot 2021-06-22 at 15 58 55](https://user-images.githubusercontent.com/19281761/122938251-e3696600-d372-11eb-9aeb-2d95c6854153.png)

I'm testing on iPhone 11 simulator, setting the height (in container style) to 791. with 790 works fine :)

**Comment by ammarahm-ed** [comment]
Hey @mateattilabarna. You were right, the issue was still existing. I fixed it now. Test using master branch.

**Comment by mateattilabarna** [comment]
Hi @ammarahm-ed ,

I tried out with the latest master, unfortunately still doesn't work for me :(

**Comment by mateattilabarna** [comment]
@ammarahm-ed 

I did it, I can see the latest changes, e.g.:

![Screenshot 2021-06-22 at 18 40 23](https://user-images.githubusercontent.com/19281761/122966625-d441e280-d389-11eb-8a42-7a33467d3108.png)

If I have 1 action sheet, it doesn't work. If I have 2 action sheets, then which i open firstly that's wrong and which i open secondly that's working fine.

**Comment by ammarahm-ed** [comment]
Hey @mateattilabarna It is working normally for me. I have still made a couple of changes again. Try once more. 

If you still face the same issue, set `drawUnderStatusBar` to `false`.

**Comment by ammarahm-ed** [comment]
> Hey @mateattilabarna It is working normally for me. I have still made a couple of changes again. Try once more.
> 
> If you still face the same issue, set `drawUnderStatusBar` to `false`.

**Comment by mateattilabarna** [comment]
Hi @ammarahm-ed,

With setting the **drawUnderStatusBar**  to **false** it's working for me.

**Comment by mateattilabarna** [comment]
@ammarahm-ed 

Another topic (I can open another ticket if you want):

inside the ActionSheet i want to use Flatlist/Scrollview. I tried out with ScrollView and it works. The Flatlist unfortunately doesn't scroll :( i followed the documentation. Do you have any idea?

**Comment by ammarahm-ed** [comment]
This issue will help, https://github.com/ammarahm-ed/react-native-actions-sheet/issues/68

**Comment by mateattilabarna** [comment]
@ammarahm-ed 

Thank you!
Fyi: From me  using Flatlist from react-native-gesture-handler works only.

When you plan to release a new library version?

**Comment by mateattilabarna** [comment]
@ammarahm-ed

Hi! When you plan to release the new version of the library?

**Comment by ammarahm-ed** [comment]
@mateattilabarna I want to release it soon. Actually I have converted the whole lib code to typescript to facilitate future development. However I am not a typescript expert and I need some help in checking the code and possible `ts-check` errors especially `strictNullChecks`.

**Comment by mateattilabarna** [comment]
@ammarahm-ed Let me know if I can help you!

Do you have any date for the release? We would like to have the fixes, but would need a fix version.

**Comment by GianMantuan** [comment]
I can confirm that the issue still happens, however, if you set `drawUnderStatusBar` to `false` as mentioned by @ammarahm-ed the issue is resolved.
